package com.straw.friend.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.straw.friend.bean.Circle;
@Repository 
public interface ICircleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle
     *
     * @mbggenerated
     */
    int insert(Circle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle
     *
     * @mbggenerated
     */
    int insertSelective(Circle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle
     *
     * @mbggenerated
     */
    Circle selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Circle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Circle record);
    
	int findAccount();

	List<Circle> findCircleNoByUserId(String userId);

	int selectCircleByIdPd(String Id, String passString);
}