package com.straw.friend.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.straw.friend.bean.Joke;
@Repository 
public interface IJokeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joke
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joke
     *
     * @mbggenerated
     */
    int insert(Joke record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joke
     *
     * @mbggenerated
     */
    int insertSelective(Joke record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joke
     *
     * @mbggenerated
     */
    Joke selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joke
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Joke record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joke
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Joke record);

	List<Joke> findList();
}