package com.straw.friend.dao;

import org.springframework.stereotype.Repository;

import com.straw.friend.bean.OaPrivilege;
@Repository 
public interface OaPrivilegeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_privilege
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_privilege
     *
     * @mbggenerated
     */
    int insert(OaPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_privilege
     *
     * @mbggenerated
     */
    int insertSelective(OaPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_privilege
     *
     * @mbggenerated
     */
    OaPrivilege selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_privilege
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OaPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_privilege
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OaPrivilege record);
}