package com.straw.friend.dao;

import com.straw.friend.bean.OaResource;

public interface OaResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_resource
     *
     * @mbggenerated
     */
    int insert(OaResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_resource
     *
     * @mbggenerated
     */
    int insertSelective(OaResource record);
}