package com.straw.friend.dao;

import org.springframework.stereotype.Repository;

import com.straw.friend.bean.OaResource;
@Repository 
public interface OaResourceDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_resource
     *
     * @mbggenerated
     */
    int insert(OaResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_resource
     *
     * @mbggenerated
     */
    int insertSelective(OaResource record);
}