package com.straw.friend.dao;

import org.springframework.stereotype.Repository;

import com.straw.friend.bean.OaRole;
@Repository 
public interface OaRoleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_role
     *
     * @mbggenerated
     */
    int insert(OaRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_role
     *
     * @mbggenerated
     */
    int insertSelective(OaRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_role
     *
     * @mbggenerated
     */
    OaRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OaRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OaRole record);
}