package com.straw.friend.dao;

import org.springframework.stereotype.Repository;

import com.straw.friend.bean.OaUserRole;
@Repository 
public interface OaUserRoleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_user_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_user_role
     *
     * @mbggenerated
     */
    int insert(OaUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_user_role
     *
     * @mbggenerated
     */
    int insertSelective(OaUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_user_role
     *
     * @mbggenerated
     */
    OaUserRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OaUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OaUserRole record);
}