package com.straw.friend.bean;

import java.util.Date;
import java.util.UUID;

public class Joke {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joke.id
     *
     * @mbggenerated
     */
    private String id = UUID.randomUUID().toString();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joke.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joke.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joke.createdate
     *
     * @mbggenerated
     */
    private Date createdate = new Date();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joke.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joke.id
     *
     * @return the value of joke.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joke.id
     *
     * @param id the value for joke.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joke.title
     *
     * @return the value of joke.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joke.title
     *
     * @param title the value for joke.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joke.content
     *
     * @return the value of joke.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joke.content
     *
     * @param content the value for joke.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joke.createdate
     *
     * @return the value of joke.createdate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joke.createdate
     *
     * @param createdate the value for joke.createdate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joke.userid
     *
     * @return the value of joke.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joke.userid
     *
     * @param userid the value for joke.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }
}