package com.straw.friend.bean;

public class OaResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_resource.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_resource.resource_key
     *
     * @mbggenerated
     */
    private String resourceKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_resource.resource_name
     *
     * @mbggenerated
     */
    private String resourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_resource.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_resource.big_icon
     *
     * @mbggenerated
     */
    private String bigIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_resource.small_icon
     *
     * @mbggenerated
     */
    private String smallIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_resource.depth_
     *
     * @mbggenerated
     */
    private Integer depth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_resource.lay_order
     *
     * @mbggenerated
     */
    private Integer layOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_resource.target_
     *
     * @mbggenerated
     */
    private String target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_resource.url_
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_resource.hidden_
     *
     * @mbggenerated
     */
    private Integer hidden;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_resource.description_
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_resource.id
     *
     * @return the value of oa_resource.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_resource.id
     *
     * @param id the value for oa_resource.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_resource.resource_key
     *
     * @return the value of oa_resource.resource_key
     *
     * @mbggenerated
     */
    public String getResourceKey() {
        return resourceKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_resource.resource_key
     *
     * @param resourceKey the value for oa_resource.resource_key
     *
     * @mbggenerated
     */
    public void setResourceKey(String resourceKey) {
        this.resourceKey = resourceKey == null ? null : resourceKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_resource.resource_name
     *
     * @return the value of oa_resource.resource_name
     *
     * @mbggenerated
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_resource.resource_name
     *
     * @param resourceName the value for oa_resource.resource_name
     *
     * @mbggenerated
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_resource.parent_id
     *
     * @return the value of oa_resource.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_resource.parent_id
     *
     * @param parentId the value for oa_resource.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_resource.big_icon
     *
     * @return the value of oa_resource.big_icon
     *
     * @mbggenerated
     */
    public String getBigIcon() {
        return bigIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_resource.big_icon
     *
     * @param bigIcon the value for oa_resource.big_icon
     *
     * @mbggenerated
     */
    public void setBigIcon(String bigIcon) {
        this.bigIcon = bigIcon == null ? null : bigIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_resource.small_icon
     *
     * @return the value of oa_resource.small_icon
     *
     * @mbggenerated
     */
    public String getSmallIcon() {
        return smallIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_resource.small_icon
     *
     * @param smallIcon the value for oa_resource.small_icon
     *
     * @mbggenerated
     */
    public void setSmallIcon(String smallIcon) {
        this.smallIcon = smallIcon == null ? null : smallIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_resource.depth_
     *
     * @return the value of oa_resource.depth_
     *
     * @mbggenerated
     */
    public Integer getDepth() {
        return depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_resource.depth_
     *
     * @param depth the value for oa_resource.depth_
     *
     * @mbggenerated
     */
    public void setDepth(Integer depth) {
        this.depth = depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_resource.lay_order
     *
     * @return the value of oa_resource.lay_order
     *
     * @mbggenerated
     */
    public Integer getLayOrder() {
        return layOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_resource.lay_order
     *
     * @param layOrder the value for oa_resource.lay_order
     *
     * @mbggenerated
     */
    public void setLayOrder(Integer layOrder) {
        this.layOrder = layOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_resource.target_
     *
     * @return the value of oa_resource.target_
     *
     * @mbggenerated
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_resource.target_
     *
     * @param target the value for oa_resource.target_
     *
     * @mbggenerated
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_resource.url_
     *
     * @return the value of oa_resource.url_
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_resource.url_
     *
     * @param url the value for oa_resource.url_
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_resource.hidden_
     *
     * @return the value of oa_resource.hidden_
     *
     * @mbggenerated
     */
    public Integer getHidden() {
        return hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_resource.hidden_
     *
     * @param hidden the value for oa_resource.hidden_
     *
     * @mbggenerated
     */
    public void setHidden(Integer hidden) {
        this.hidden = hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_resource.description_
     *
     * @return the value of oa_resource.description_
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_resource.description_
     *
     * @param description the value for oa_resource.description_
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}