package com.straw.friend.bean;

public class OaRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_role.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_role.role_name
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_role.directory_id
     *
     * @mbggenerated
     */
    private String directoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_role.description_
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_role.id
     *
     * @return the value of oa_role.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_role.id
     *
     * @param id the value for oa_role.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_role.role_name
     *
     * @return the value of oa_role.role_name
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_role.role_name
     *
     * @param roleName the value for oa_role.role_name
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_role.directory_id
     *
     * @return the value of oa_role.directory_id
     *
     * @mbggenerated
     */
    public String getDirectoryId() {
        return directoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_role.directory_id
     *
     * @param directoryId the value for oa_role.directory_id
     *
     * @mbggenerated
     */
    public void setDirectoryId(String directoryId) {
        this.directoryId = directoryId == null ? null : directoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_role.description_
     *
     * @return the value of oa_role.description_
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_role.description_
     *
     * @param description the value for oa_role.description_
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}