package com.straw.friend.bean;

public class OaRoleResourcePrivilege {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_role_resource_privilege.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_role_resource_privilege.privilege_id
     *
     * @mbggenerated
     */
    private String privilegeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_role_resource_privilege.role_resource_id
     *
     * @mbggenerated
     */
    private String roleResourceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_role_resource_privilege.id
     *
     * @return the value of oa_role_resource_privilege.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_role_resource_privilege.id
     *
     * @param id the value for oa_role_resource_privilege.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_role_resource_privilege.privilege_id
     *
     * @return the value of oa_role_resource_privilege.privilege_id
     *
     * @mbggenerated
     */
    public String getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_role_resource_privilege.privilege_id
     *
     * @param privilegeId the value for oa_role_resource_privilege.privilege_id
     *
     * @mbggenerated
     */
    public void setPrivilegeId(String privilegeId) {
        this.privilegeId = privilegeId == null ? null : privilegeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_role_resource_privilege.role_resource_id
     *
     * @return the value of oa_role_resource_privilege.role_resource_id
     *
     * @mbggenerated
     */
    public String getRoleResourceId() {
        return roleResourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_role_resource_privilege.role_resource_id
     *
     * @param roleResourceId the value for oa_role_resource_privilege.role_resource_id
     *
     * @mbggenerated
     */
    public void setRoleResourceId(String roleResourceId) {
        this.roleResourceId = roleResourceId == null ? null : roleResourceId.trim();
    }
}