package com.straw.friend.bean;

import java.util.Date;

public class OaUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_user.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_user.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_user.directory_id
     *
     * @mbggenerated
     */
    private String directoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_user.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_user.email_
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_user.list_order
     *
     * @mbggenerated
     */
    private Integer listOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_user.pwd_format
     *
     * @mbggenerated
     */
    private String pwdFormat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_user.password_
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_user.approved_
     *
     * @mbggenerated
     */
    private Boolean approved;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_user.locked_out
     *
     * @mbggenerated
     */
    private Boolean lockedOut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_user.last_lockout_date
     *
     * @mbggenerated
     */
    private Date lastLockoutDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_user.question_
     *
     * @mbggenerated
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_user.answer_
     *
     * @mbggenerated
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_user.failed_answer_date
     *
     * @mbggenerated
     */
    private Date failedAnswerDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_user.failed_answer_count
     *
     * @mbggenerated
     */
    private Integer failedAnswerCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_user.failed_date
     *
     * @mbggenerated
     */
    private Date failedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_user.failed_count
     *
     * @mbggenerated
     */
    private Integer failedCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_user.last_login_date
     *
     * @mbggenerated
     */
    private Date lastLoginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_user.last_pwd_change
     *
     * @mbggenerated
     */
    private Date lastPwdChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_user.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_user.Salt
     *
     * @mbggenerated
     */
    private String salt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_user.id
     *
     * @return the value of oa_user.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_user.id
     *
     * @param id the value for oa_user.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_user.user_id
     *
     * @return the value of oa_user.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_user.user_id
     *
     * @param userId the value for oa_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_user.directory_id
     *
     * @return the value of oa_user.directory_id
     *
     * @mbggenerated
     */
    public String getDirectoryId() {
        return directoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_user.directory_id
     *
     * @param directoryId the value for oa_user.directory_id
     *
     * @mbggenerated
     */
    public void setDirectoryId(String directoryId) {
        this.directoryId = directoryId == null ? null : directoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_user.user_name
     *
     * @return the value of oa_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_user.user_name
     *
     * @param userName the value for oa_user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_user.real_name
     *
     * @return the value of oa_user.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_user.real_name
     *
     * @param realName the value for oa_user.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_user.email_
     *
     * @return the value of oa_user.email_
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_user.email_
     *
     * @param email the value for oa_user.email_
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_user.list_order
     *
     * @return the value of oa_user.list_order
     *
     * @mbggenerated
     */
    public Integer getListOrder() {
        return listOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_user.list_order
     *
     * @param listOrder the value for oa_user.list_order
     *
     * @mbggenerated
     */
    public void setListOrder(Integer listOrder) {
        this.listOrder = listOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_user.pwd_format
     *
     * @return the value of oa_user.pwd_format
     *
     * @mbggenerated
     */
    public String getPwdFormat() {
        return pwdFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_user.pwd_format
     *
     * @param pwdFormat the value for oa_user.pwd_format
     *
     * @mbggenerated
     */
    public void setPwdFormat(String pwdFormat) {
        this.pwdFormat = pwdFormat == null ? null : pwdFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_user.password_
     *
     * @return the value of oa_user.password_
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_user.password_
     *
     * @param password the value for oa_user.password_
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_user.approved_
     *
     * @return the value of oa_user.approved_
     *
     * @mbggenerated
     */
    public Boolean getApproved() {
        return approved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_user.approved_
     *
     * @param approved the value for oa_user.approved_
     *
     * @mbggenerated
     */
    public void setApproved(Boolean approved) {
        this.approved = approved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_user.locked_out
     *
     * @return the value of oa_user.locked_out
     *
     * @mbggenerated
     */
    public Boolean getLockedOut() {
        return lockedOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_user.locked_out
     *
     * @param lockedOut the value for oa_user.locked_out
     *
     * @mbggenerated
     */
    public void setLockedOut(Boolean lockedOut) {
        this.lockedOut = lockedOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_user.last_lockout_date
     *
     * @return the value of oa_user.last_lockout_date
     *
     * @mbggenerated
     */
    public Date getLastLockoutDate() {
        return lastLockoutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_user.last_lockout_date
     *
     * @param lastLockoutDate the value for oa_user.last_lockout_date
     *
     * @mbggenerated
     */
    public void setLastLockoutDate(Date lastLockoutDate) {
        this.lastLockoutDate = lastLockoutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_user.question_
     *
     * @return the value of oa_user.question_
     *
     * @mbggenerated
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_user.question_
     *
     * @param question the value for oa_user.question_
     *
     * @mbggenerated
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_user.answer_
     *
     * @return the value of oa_user.answer_
     *
     * @mbggenerated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_user.answer_
     *
     * @param answer the value for oa_user.answer_
     *
     * @mbggenerated
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_user.failed_answer_date
     *
     * @return the value of oa_user.failed_answer_date
     *
     * @mbggenerated
     */
    public Date getFailedAnswerDate() {
        return failedAnswerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_user.failed_answer_date
     *
     * @param failedAnswerDate the value for oa_user.failed_answer_date
     *
     * @mbggenerated
     */
    public void setFailedAnswerDate(Date failedAnswerDate) {
        this.failedAnswerDate = failedAnswerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_user.failed_answer_count
     *
     * @return the value of oa_user.failed_answer_count
     *
     * @mbggenerated
     */
    public Integer getFailedAnswerCount() {
        return failedAnswerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_user.failed_answer_count
     *
     * @param failedAnswerCount the value for oa_user.failed_answer_count
     *
     * @mbggenerated
     */
    public void setFailedAnswerCount(Integer failedAnswerCount) {
        this.failedAnswerCount = failedAnswerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_user.failed_date
     *
     * @return the value of oa_user.failed_date
     *
     * @mbggenerated
     */
    public Date getFailedDate() {
        return failedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_user.failed_date
     *
     * @param failedDate the value for oa_user.failed_date
     *
     * @mbggenerated
     */
    public void setFailedDate(Date failedDate) {
        this.failedDate = failedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_user.failed_count
     *
     * @return the value of oa_user.failed_count
     *
     * @mbggenerated
     */
    public Integer getFailedCount() {
        return failedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_user.failed_count
     *
     * @param failedCount the value for oa_user.failed_count
     *
     * @mbggenerated
     */
    public void setFailedCount(Integer failedCount) {
        this.failedCount = failedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_user.last_login_date
     *
     * @return the value of oa_user.last_login_date
     *
     * @mbggenerated
     */
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_user.last_login_date
     *
     * @param lastLoginDate the value for oa_user.last_login_date
     *
     * @mbggenerated
     */
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_user.last_pwd_change
     *
     * @return the value of oa_user.last_pwd_change
     *
     * @mbggenerated
     */
    public Date getLastPwdChange() {
        return lastPwdChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_user.last_pwd_change
     *
     * @param lastPwdChange the value for oa_user.last_pwd_change
     *
     * @mbggenerated
     */
    public void setLastPwdChange(Date lastPwdChange) {
        this.lastPwdChange = lastPwdChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_user.create_date
     *
     * @return the value of oa_user.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_user.create_date
     *
     * @param createDate the value for oa_user.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_user.Salt
     *
     * @return the value of oa_user.Salt
     *
     * @mbggenerated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_user.Salt
     *
     * @param salt the value for oa_user.Salt
     *
     * @mbggenerated
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }
}